// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// best_gs_bucket_cpp
DataFrame best_gs_bucket_cpp(List men_prefs, List women_prefs);
RcppExport SEXP _CHTpackage_best_gs_bucket_cpp(SEXP men_prefsSEXP, SEXP women_prefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type men_prefs(men_prefsSEXP);
    Rcpp::traits::input_parameter< List >::type women_prefs(women_prefsSEXP);
    rcpp_result_gen = Rcpp::wrap(best_gs_bucket_cpp(men_prefs, women_prefs));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _CHTpackage_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CHTpackage_best_gs_bucket_cpp", (DL_FUNC) &_CHTpackage_best_gs_bucket_cpp, 2},
    {"_CHTpackage_rcpp_hello", (DL_FUNC) &_CHTpackage_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CHTpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
