// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// best_gs_heap_cpp
DataFrame best_gs_heap_cpp(List men_prefs, List women_prefs);
RcppExport SEXP _CHTpackage_best_gs_heap_cpp(SEXP men_prefsSEXP, SEXP women_prefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type men_prefs(men_prefsSEXP);
    Rcpp::traits::input_parameter< List >::type women_prefs(women_prefsSEXP);
    rcpp_result_gen = Rcpp::wrap(best_gs_heap_cpp(men_prefs, women_prefs));
    return rcpp_result_gen;
END_RCPP
}
// can_receive_cpp
bool can_receive_cpp(const std::string& donor_type, const std::string& recipient_type, const NumericMatrix& compatibility_table, const CharacterVector& blood_types);
RcppExport SEXP _CHTpackage_can_receive_cpp(SEXP donor_typeSEXP, SEXP recipient_typeSEXP, SEXP compatibility_tableSEXP, SEXP blood_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type donor_type(donor_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type recipient_type(recipient_typeSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type compatibility_table(compatibility_tableSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type blood_types(blood_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(can_receive_cpp(donor_type, recipient_type, compatibility_table, blood_types));
    return rcpp_result_gen;
END_RCPP
}
// build_compatibility_graph_cpp
List build_compatibility_graph_cpp(const IntegerVector& donors, const IntegerVector& receivers, const DataFrame& data, const NumericMatrix& compatibility_table, const CharacterVector& blood_types);
RcppExport SEXP _CHTpackage_build_compatibility_graph_cpp(SEXP donorsSEXP, SEXP receiversSEXP, SEXP dataSEXP, SEXP compatibility_tableSEXP, SEXP blood_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type donors(donorsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receivers(receiversSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type compatibility_table(compatibility_tableSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type blood_types(blood_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(build_compatibility_graph_cpp(donors, receivers, data, compatibility_table, blood_types));
    return rcpp_result_gen;
END_RCPP
}
// hopcroft_karp_cpp
List hopcroft_karp_cpp(const IntegerVector& donors, const IntegerVector& receivers, const DataFrame& data, const NumericMatrix& compatibility_table, const CharacterVector& blood_types);
RcppExport SEXP _CHTpackage_hopcroft_karp_cpp(SEXP donorsSEXP, SEXP receiversSEXP, SEXP dataSEXP, SEXP compatibility_tableSEXP, SEXP blood_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type donors(donorsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receivers(receiversSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type compatibility_table(compatibility_tableSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type blood_types(blood_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(hopcroft_karp_cpp(donors, receivers, data, compatibility_table, blood_types));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _CHTpackage_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CHTpackage_best_gs_heap_cpp", (DL_FUNC) &_CHTpackage_best_gs_heap_cpp, 2},
    {"_CHTpackage_can_receive_cpp", (DL_FUNC) &_CHTpackage_can_receive_cpp, 4},
    {"_CHTpackage_build_compatibility_graph_cpp", (DL_FUNC) &_CHTpackage_build_compatibility_graph_cpp, 5},
    {"_CHTpackage_hopcroft_karp_cpp", (DL_FUNC) &_CHTpackage_hopcroft_karp_cpp, 5},
    {"_CHTpackage_rcpp_hello", (DL_FUNC) &_CHTpackage_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CHTpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
