# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gale-Shapley Stable Matching Algorithm
NULL

gale_shapley_cpp <- function(men_prefs, women_prefs) {
    .Call(`_CHTpackage_gale_shapley_cpp`, men_prefs, women_prefs)
}

#' Best-First Gale-Shapley (Bucket Version)
NULL

best_gs_bucket_cpp <- function(men_prefs, women_prefs) {
    .Call(`_CHTpackage_best_gs_bucket_cpp`, men_prefs, women_prefs)
}

#' Build Compatibility Graph
NULL

#' Hopcroft-Karp Maximum Bipartite Matching Algorithm
NULL

build_compatibility_graph_cpp <- function(donors, receivers, data, compatibility_table, blood_types) {
    .Call(`_CHTpackage_build_compatibility_graph_cpp`, donors, receivers, data, compatibility_table, blood_types)
}

hopcroft_karp_cpp <- function(donors, receivers, data, compatibility_table, blood_types) {
    .Call(`_CHTpackage_hopcroft_karp_cpp`, donors, receivers, data, compatibility_table, blood_types)
}

